# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Copy'
    connection: 'Artifactory-vj'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "test-generic-local/upload-folder/file8.txt",
            "target": "test11-generic-local/file8.txt"
          }
        ]
      }
    dryRun: true
    failNoOp: true

