# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'Artifactory-vj'
    targetResolveReleaseRepo: 'vj-libs-release'
    targetResolveSnapshotRepo: 'vj-libs-snapshot'
    artifactoryDeployService: 'Artifactory-vj'
    targetDeployReleaseRepo: 'vj-libs-release-local'
    targetDeploySnapshotRepo: 'vj-libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'Artifactory-vj'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'vj-xray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: false

